[package]
name = "radio-s2lp"
description = "Driver for the ST S2-LP Sub 1GHz ISM band radio IC"
version = "0.1.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]

[dependencies]
embedded-hal = { version = "0.2.2", features = ["unproven"] }
nb = "0.1.1"
radio = { path = "../rust-radio" }

[dev-dependencies]
embedded-hal-mock = { version = "0.5.0" }

[patch.crates-io]
#embedded-hal = { git="https://github.com/ryankurte/embedded-hal", branch = "feature/digital-compat-shims-a" }
#embedded-hal-mock = { git = "https://github.com/ryankurte/embedded-hal-mock", branch = "feature/pins" }
embedded-hal = { git = "https://github.com/rust-embedded/embedded-hal" }
embedded-hal-mock = { path = "../embedded-hal-mock" }
